[project]
name = "lidl-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "playwright>=1.55.0",
    "python-dotenv>=1.2.1",
]
